secrets:
  - secretEnv:
      VITE_GOOGLE_OAUTH_CLIENT_ID: projects/1094631205138/secrets/VITE_GOOGLE_OAUTH_CLIENT_ID/versions/latest

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/bold-bastion-454011-k5/frontend-app'
      - '--build-arg'
      - 'VITE_GOOGLE_OAUTH_CLIENT_ID=$VITE_GOOGLE_OAUTH_CLIENT_ID'
      - './frontend'
    secretEnv: ['VITE_GOOGLE_OAUTH_CLIENT_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/bold-bastion-454011-k5/frontend-app']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'frontend-app'
      - '--image=gcr.io/bold-bastion-454011-k5/frontend-app'
      - '--platform=managed'
      - '--region=us-central1'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/bold-bastion-454011-k5/frontend-app'

options:
  logging: CLOUD_LOGGING_ONLY
