# Generated by Django 4.2.20 on 2025-03-19 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_lat', models.FloatField()),
                ('start_lon', models.FloatField()),
                ('start_name', models.CharField(max_length=255)),
                ('end_lat', models.FloatField()),
                ('end_lon', models.FloatField()),
                ('end_name', models.CharField(max_length=255)),
                ('route_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_routes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoutePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(choices=[('fastest', 'En Hızlı'), ('shortest', 'En Kısa'), ('balanced', 'Dengeli')], default='balanced', max_length=20)),
                ('avoid_highways', models.BooleanField(default=False)),
                ('avoid_tolls', models.BooleanField(default=False)),
                ('avoid_ferries', models.BooleanField(default=False)),
                ('traffic_priority', models.CharField(choices=[('avoid', 'Trafikten Kaçın'), ('moderate', 'Orta Seviye'), ('ignore', 'Trafiği Önemseme')], default='moderate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
