# Generated by Django 4.2.20 on 2025-03-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WiFiPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='İsim')),
                ('address', models.CharField(max_length=500, verbose_name='Adres')),
                ('category', models.CharField(default='Wifi Noktası', max_length=100, verbose_name='Kategori')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('latitude', models.FloatField(verbose_name='Enlem')),
                ('longitude', models.FloatField(verbose_name='Boylam')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'WiFi Noktası',
                'verbose_name_plural': 'WiFi Noktaları',
            },
        ),
    ]
