# Generated by Django 4.2.20 on 2025-03-21 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_points', '0001_initial'),
    ]

    operations = [
    ]
