# Generated by Django 4.2.20 on 2025-03-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BicyclePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='İsim')),
                ('global_id', models.CharField(max_length=255, unique=True, verbose_name='Global ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('latitude', models.FloatField(verbose_name='Enlem')),
                ('longitude', models.FloatField(verbose_name='Boylam')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'Bisiklet İstasyonu',
                'verbose_name_plural': 'Bisiklet İstasyonları',
            },
        ),
    ]
