# Generated by Django 4.2.20 on 2025-04-25 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_remove_userprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(unique=True, verbose_name='OSM Way ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Road Name')),
                ('road_type', models.CharField(blank=True, max_length=50, verbose_name='Road Type')),
                ('start_node', models.BigIntegerField(verbose_name='Start Node ID')),
                ('end_node', models.BigIntegerField(verbose_name='End Node ID')),
                ('geometry', models.TextField(blank=True, null=True, verbose_name='Road Geometry (GeoJSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Road Segment',
                'verbose_name_plural': 'Road Segments',
            },
        ),
        migrations.CreateModel(
            name='UserRoadPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(choices=[('prefer', 'Prefer this road'), ('avoid', 'Avoid this road')], max_length=10, verbose_name='Preference Type')),
                ('reason', models.TextField(blank=True, verbose_name='Reason for Preference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('road_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='routing.roadsegment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='road_preferences', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'User Road Preference',
                'verbose_name_plural': 'User Road Preferences',
            },
        ),
        migrations.CreateModel(
            name='RoutePreferenceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Profile Name')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Profile')),
                ('description', models.TextField(blank=True, verbose_name='Profile Description')),
                ('prefer_multiplier', models.FloatField(default=0.75, verbose_name='Preferred Road Multiplier')),
                ('avoid_multiplier', models.FloatField(default=3.0, verbose_name='Avoided Road Multiplier')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_profiles', to='users.userprofile')),
            ],
            options={
                'verbose_name': 'Route Preference Profile',
                'verbose_name_plural': 'Route Preference Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='roadsegment',
            index=models.Index(fields=['osm_id'], name='routing_roa_osm_id_953006_idx'),
        ),
        migrations.AddIndex(
            model_name='roadsegment',
            index=models.Index(fields=['name'], name='routing_roa_name_ffe446_idx'),
        ),
        migrations.AddIndex(
            model_name='roadsegment',
            index=models.Index(fields=['road_type'], name='routing_roa_road_ty_1f4acd_idx'),
        ),
        migrations.AddIndex(
            model_name='userroadpreference',
            index=models.Index(fields=['user'], name='routing_use_user_id_379971_idx'),
        ),
        migrations.AddIndex(
            model_name='userroadpreference',
            index=models.Index(fields=['preference_type'], name='routing_use_prefere_22da4e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userroadpreference',
            unique_together={('user', 'road_segment')},
        ),
        migrations.AddIndex(
            model_name='routepreferenceprofile',
            index=models.Index(fields=['user'], name='routing_rou_user_id_4cd554_idx'),
        ),
        migrations.AddIndex(
            model_name='routepreferenceprofile',
            index=models.Index(fields=['is_default'], name='routing_rou_is_defa_42d496_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='routepreferenceprofile',
            unique_together={('user', 'name')},
        ),
    ]
