# Generated by Django 4.2.20 on 2025-03-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Eczane Adı')),
                ('address', models.TextField(verbose_name='Adres')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Bölge')),
                ('extra_info', models.TextField(blank=True, verbose_name='Ek Bilgi')),
                ('date', models.DateField(verbose_name='Tarih')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nöbetçi Eczane',
                'verbose_name_plural': 'Nöbetçi Eczaneler',
                'ordering': ['-date', 'district', 'name'],
                'unique_together': {('name', 'date')},
            },
        ),
    ]
